import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// components/Layout.js
import React, { ReactNode } from 'react';

interface LayoutProps {
    children: ReactNode;
}

const Layout: React.FC<LayoutProps> = ({ children }) => {
    return (
        <div className="flex flex-col h-screen">
            <Navbar></Navbar>
            <main className="flex-1 p-4">{children}</main>
        </div>
    );
};

const Navbar : any = () => {
    let  textColor : string = "text-blue-950";
    return (
        <>
            <header className="bg-white p-4">
                <nav className="flex items-center justify-between">
                    <div className={textColor + " font-bold"}>Bear Advisor Scheduler</div>
                    <div className="space-x-8">
                        <a href="#" className={textColor}>About</a>
                        <a href="#" className={textColor}>Sign in</a>
                        <a href="#" className={textColor}>Log in</a>
                    </div>
                </nav>
            </header>
        </>
    )
}
export default Layout;



